### ISSUE TITLE
How to use this with Widgets?

### ISSUE THREAD

**Issue by Ahmadre** [LUK3D/do_tween#1]
Thank you for your package, but I'm irritated in the short examples how to use this exactly for my widgets?

Do you have a full/complete example with simple widgets?

**Comment by LUK3D** [comment]
> Thank you for your package, but I'm irritated in the short examples how to use this exactly for my widgets?
> 
> Do you have a full/complete example with simple widgets?

With this package you can animate a numerical value over time. You can then use the value with sets setState to animate a widget. 

Take a look on this package source code. It uses Do_Tween to create an animated button for recording audio just like WhatsApp.
 https://pub.dev/packages/animated_chat_action_button

**Comment by Ahmadre** [comment]
> > Thank you for your package, but I'm irritated in the short examples how to use this exactly for my widgets?
> > Do you have a full/complete example with simple widgets?
> 
> With this package you can animate a numerical value over time. You can then use the value with sets setState to animate a widget.
> 
> Take a look on this package source code. It uses Do_Tween to create an animated button for recording audio just like WhatsApp. https://pub.dev/packages/animated_chat_action_button

awesome :) thx for the hint.
